# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  push:
    branches:
      - main
  pull_request:


permissions: {}

jobs:
  ci:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - run: |
          go build ./...
